# Generated by Django 5.2.11 on 2026-02-10 16:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('entrada', models.BooleanField(default=False)),
                ('cor', models.CharField(default='#FFFFFF', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True, max_length=100, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_lancamento', models.DateField(verbose_name='Data de Lançamento')),
                ('tipo', models.CharField(choices=[('Fixa', 'Fixa'), ('Única', 'Única'), ('Parcelada', 'Parcelada')], default='Única', max_length=10)),
                ('situacao', models.CharField(choices=[('PAGA', 'Paga'), ('PENDENTE', 'Pendente'), ('ATRASADA', 'Atrasada')], default='PENDENTE', max_length=10)),
                ('parcela_atual', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('total_parcelas', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('identificador_transacao', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('data_criacao', models.DateField(verbose_name='Data de Criação')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.categoria')),
            ],
            options={
                'ordering': ['-data_vencimento'],
            },
        ),
    ]
