# Generated by Django 5.2.11 on 2026-02-10 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conta',
            new_name='Transacao',
        ),
    ]
