# Generated by Django 5.2.11 on 2026-02-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_conta_transacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transacao',
            options={'ordering': ['-data_criacao']},
        ),
        migrations.AlterField(
            model_name='transacao',
            name='tipo',
            field=models.CharField(choices=[('Única', 'Única'), ('Fixa', 'Fixa'), ('Parcelada', 'Parcelada')], default='Única', max_length=10),
        ),
    ]
