# Generated by Django 5.2.11 on 2026-02-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_transacao_options_alter_transacao_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data_criacao',
            field=models.DateField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
    ]
