# Generated by Django 5.2.11 on 2026-02-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_transacao_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
    ]
